;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/acm
  (:use)
  (:nicknames #:aws/acm)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/acm)
(common-lisp:progn
 (common-lisp:defstruct
     (add-tags-to-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (tags (common-lisp:error ":tags is required") :type
    (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'add-tags-to-certificate-request
                    'make-add-tags-to-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          add-tags-to-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Tags"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tags))))))
(common-lisp:deftype arn () 'common-lisp:string)
(common-lisp:deftype certificate-body () 'common-lisp:string)
(common-lisp:deftype certificate-body-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype certificate-chain () 'common-lisp:string)
(common-lisp:deftype certificate-chain-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:progn
 (common-lisp:defstruct (certificate-detail (:copier common-lisp:nil))
   (certificate-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null))
   (domain-name common-lisp:nil :type
    (common-lisp:or domain-name-string common-lisp:null))
   (subject-alternative-names common-lisp:nil :type
    (common-lisp:or domain-list common-lisp:null))
   (domain-validation-options common-lisp:nil :type
    (common-lisp:or domain-validation-list common-lisp:null))
   (serial common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (subject common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (issuer common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (created-at common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (issued-at common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (imported-at common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or certificate-status common-lisp:null))
   (revoked-at common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (revocation-reason common-lisp:nil :type
    (common-lisp:or revocation-reason common-lisp:null))
   (not-before common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (not-after common-lisp:nil :type (common-lisp:or tstamp common-lisp:null))
   (key-algorithm common-lisp:nil :type
    (common-lisp:or key-algorithm common-lisp:null))
   (signature-algorithm common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (in-use-by common-lisp:nil :type
    (common-lisp:or in-use-list common-lisp:null))
   (failure-reason common-lisp:nil :type
    (common-lisp:or failure-reason common-lisp:null))
   (type common-lisp:nil :type
    (common-lisp:or certificate-type common-lisp:null))
   (renewal-summary common-lisp:nil :type
    (common-lisp:or renewal-summary common-lisp:null))
   (key-usages common-lisp:nil :type
    (common-lisp:or key-usage-list common-lisp:null))
   (extended-key-usages common-lisp:nil :type
    (common-lisp:or extended-key-usage-list common-lisp:null))
   (certificate-authority-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null))
   (renewal-eligibility common-lisp:nil :type
    (common-lisp:or renewal-eligibility common-lisp:null))
   (options common-lisp:nil :type
    (common-lisp:or certificate-options common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'certificate-detail 'make-certificate-detail))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape certificate-detail))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "DomainName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-name)))
    (aws-sdk/generator/shape::to-query-params "SubjectAlternativeNames"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subject-alternative-names)))
    (aws-sdk/generator/shape::to-query-params "DomainValidationOptions"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-validation-options)))
    (aws-sdk/generator/shape::to-query-params "Serial"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'serial)))
    (aws-sdk/generator/shape::to-query-params "Subject"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subject)))
    (aws-sdk/generator/shape::to-query-params "Issuer"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'issuer)))
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "IssuedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'issued-at)))
    (aws-sdk/generator/shape::to-query-params "ImportedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'imported-at)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status)))
    (aws-sdk/generator/shape::to-query-params "RevokedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'revoked-at)))
    (aws-sdk/generator/shape::to-query-params "RevocationReason"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'revocation-reason)))
    (aws-sdk/generator/shape::to-query-params "NotBefore"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'not-before)))
    (aws-sdk/generator/shape::to-query-params "NotAfter"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'not-after)))
    (aws-sdk/generator/shape::to-query-params "KeyAlgorithm"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-algorithm)))
    (aws-sdk/generator/shape::to-query-params "SignatureAlgorithm"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'signature-algorithm)))
    (aws-sdk/generator/shape::to-query-params "InUseBy"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'in-use-by)))
    (aws-sdk/generator/shape::to-query-params "FailureReason"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'failure-reason)))
    (aws-sdk/generator/shape::to-query-params "Type"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'type)))
    (aws-sdk/generator/shape::to-query-params "RenewalSummary"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'renewal-summary)))
    (aws-sdk/generator/shape::to-query-params "KeyUsages"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-usages)))
    (aws-sdk/generator/shape::to-query-params "ExtendedKeyUsages"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'extended-key-usages)))
    (aws-sdk/generator/shape::to-query-params "CertificateAuthorityArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-authority-arn)))
    (aws-sdk/generator/shape::to-query-params "RenewalEligibility"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'renewal-eligibility)))
    (aws-sdk/generator/shape::to-query-params "Options"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'options))))))
(common-lisp:progn
 (common-lisp:defstruct (certificate-options (:copier common-lisp:nil))
   (certificate-transparency-logging-preference common-lisp:nil :type
    (common-lisp:or certificate-transparency-logging-preference
                    common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'certificate-options 'make-certificate-options))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape certificate-options))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params
     "CertificateTransparencyLoggingPreference"
     (aws-sdk/generator/shape:shape-to-params
      (common-lisp:slot-value aws-sdk/generator/shape::shape
                              'certificate-transparency-logging-preference))))))
(common-lisp:deftype certificate-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype certificate-statuses ()
   '(trivial-types:proper-list certificate-status))
 (common-lisp:defun |make-certificate-statuses|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list certificate-status))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (certificate-summary (:copier common-lisp:nil))
   (certificate-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null))
   (domain-name common-lisp:nil :type
    (common-lisp:or domain-name-string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'certificate-summary 'make-certificate-summary))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape certificate-summary))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "DomainName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-name))))))
(common-lisp:progn
 (common-lisp:deftype certificate-summary-list ()
   '(trivial-types:proper-list certificate-summary))
 (common-lisp:defun |make-certificate-summary-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list certificate-summary))
   aws-sdk/generator/shape::members))
(common-lisp:deftype certificate-transparency-logging-preference ()
  'common-lisp:string)
(common-lisp:deftype certificate-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (delete-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-certificate-request
                    'make-delete-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-certificate-request
                    'make-describe-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-certificate-response (:copier common-lisp:nil))
   (certificate common-lisp:nil :type
    (common-lisp:or certificate-detail common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-certificate-response
                    'make-describe-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Certificate"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate))))))
(common-lisp:progn
 (common-lisp:deftype domain-list ()
   '(trivial-types:proper-list domain-name-string))
 (common-lisp:defun |make-domain-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list domain-name-string))
   aws-sdk/generator/shape::members))
(common-lisp:deftype domain-name-string () 'common-lisp:string)
(common-lisp:deftype domain-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (domain-validation (:copier common-lisp:nil))
   (domain-name (common-lisp:error ":domain-name is required") :type
    (common-lisp:or domain-name-string common-lisp:null))
   (validation-emails common-lisp:nil :type
    (common-lisp:or validation-email-list common-lisp:null))
   (validation-domain common-lisp:nil :type
    (common-lisp:or domain-name-string common-lisp:null))
   (validation-status common-lisp:nil :type
    (common-lisp:or domain-status common-lisp:null))
   (resource-record common-lisp:nil :type
    (common-lisp:or resource-record common-lisp:null))
   (validation-method common-lisp:nil :type
    (common-lisp:or validation-method common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'domain-validation 'make-domain-validation))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape domain-validation))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DomainName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-name)))
    (aws-sdk/generator/shape::to-query-params "ValidationEmails"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-emails)))
    (aws-sdk/generator/shape::to-query-params "ValidationDomain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-domain)))
    (aws-sdk/generator/shape::to-query-params "ValidationStatus"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-status)))
    (aws-sdk/generator/shape::to-query-params "ResourceRecord"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'resource-record)))
    (aws-sdk/generator/shape::to-query-params "ValidationMethod"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-method))))))
(common-lisp:progn
 (common-lisp:deftype domain-validation-list ()
   '(trivial-types:proper-list domain-validation))
 (common-lisp:defun |make-domain-validation-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list domain-validation))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (domain-validation-option (:copier common-lisp:nil))
   (domain-name (common-lisp:error ":domain-name is required") :type
    (common-lisp:or domain-name-string common-lisp:null))
   (validation-domain (common-lisp:error ":validation-domain is required")
    :type (common-lisp:or domain-name-string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'domain-validation-option 'make-domain-validation-option))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          domain-validation-option))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DomainName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-name)))
    (aws-sdk/generator/shape::to-query-params "ValidationDomain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-domain))))))
(common-lisp:progn
 (common-lisp:deftype domain-validation-option-list ()
   '(trivial-types:proper-list domain-validation-option))
 (common-lisp:defun |make-domain-validation-option-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list
                            domain-validation-option))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (expiry-events-configuration (:copier common-lisp:nil))
   (days-before-expiry common-lisp:nil :type
    (common-lisp:or positive-integer common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'expiry-events-configuration
                    'make-expiry-events-configuration))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          expiry-events-configuration))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DaysBeforeExpiry"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'days-before-expiry))))))
(common-lisp:progn
 (common-lisp:defstruct (export-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (passphrase (common-lisp:error ":passphrase is required") :type
    (common-lisp:or passphrase-blob common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'export-certificate-request
                    'make-export-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          export-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Passphrase"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'passphrase))))))
(common-lisp:progn
 (common-lisp:defstruct (export-certificate-response (:copier common-lisp:nil))
   (certificate common-lisp:nil :type
    (common-lisp:or certificate-body common-lisp:null))
   (certificate-chain common-lisp:nil :type
    (common-lisp:or certificate-chain common-lisp:null))
   (private-key common-lisp:nil :type
    (common-lisp:or private-key common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'export-certificate-response
                    'make-export-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          export-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Certificate"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate)))
    (aws-sdk/generator/shape::to-query-params "CertificateChain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-chain)))
    (aws-sdk/generator/shape::to-query-params "PrivateKey"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'private-key))))))
(common-lisp:progn
 (common-lisp:defstruct (extended-key-usage (:copier common-lisp:nil))
   (name common-lisp:nil :type
    (common-lisp:or extended-key-usage-name common-lisp:null))
   (oid common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'extended-key-usage 'make-extended-key-usage))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape extended-key-usage))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "OID"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'oid))))))
(common-lisp:progn
 (common-lisp:deftype extended-key-usage-filter-list ()
   '(trivial-types:proper-list extended-key-usage-name))
 (common-lisp:defun |make-extended-key-usage-filter-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list extended-key-usage-name))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype extended-key-usage-list ()
   '(trivial-types:proper-list extended-key-usage))
 (common-lisp:defun |make-extended-key-usage-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list extended-key-usage))
   aws-sdk/generator/shape::members))
(common-lisp:deftype extended-key-usage-name () 'common-lisp:string)
(common-lisp:deftype failure-reason () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (filters (:copier common-lisp:nil))
   (extended-key-usage common-lisp:nil :type
    (common-lisp:or extended-key-usage-filter-list common-lisp:null))
   (key-usage common-lisp:nil :type
    (common-lisp:or key-usage-filter-list common-lisp:null))
   (key-types common-lisp:nil :type
    (common-lisp:or key-algorithm-list common-lisp:null)))
 (common-lisp:export (common-lisp:list 'filters 'make-filters))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape filters))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "extendedKeyUsage"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'extended-key-usage)))
    (aws-sdk/generator/shape::to-query-params "keyUsage"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-usage)))
    (aws-sdk/generator/shape::to-query-params "keyTypes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-types))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-account-configuration-response (:copier common-lisp:nil))
   (expiry-events common-lisp:nil :type
    (common-lisp:or expiry-events-configuration common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-account-configuration-response
                    'make-get-account-configuration-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-account-configuration-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ExpiryEvents"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'expiry-events))))))
(common-lisp:progn
 (common-lisp:defstruct (get-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-certificate-request 'make-get-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (get-certificate-response (:copier common-lisp:nil))
   (certificate common-lisp:nil :type
    (common-lisp:or certificate-body common-lisp:null))
   (certificate-chain common-lisp:nil :type
    (common-lisp:or certificate-chain common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-certificate-response 'make-get-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Certificate"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate)))
    (aws-sdk/generator/shape::to-query-params "CertificateChain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-chain))))))
(common-lisp:deftype idempotency-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (import-certificate-request (:copier common-lisp:nil))
   (certificate-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null))
   (certificate (common-lisp:error ":certificate is required") :type
    (common-lisp:or certificate-body-blob common-lisp:null))
   (private-key (common-lisp:error ":private-key is required") :type
    (common-lisp:or private-key-blob common-lisp:null))
   (certificate-chain common-lisp:nil :type
    (common-lisp:or certificate-chain-blob common-lisp:null))
   (tags common-lisp:nil :type (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'import-certificate-request
                    'make-import-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          import-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Certificate"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate)))
    (aws-sdk/generator/shape::to-query-params "PrivateKey"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'private-key)))
    (aws-sdk/generator/shape::to-query-params "CertificateChain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-chain)))
    (aws-sdk/generator/shape::to-query-params "Tags"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tags))))))
(common-lisp:progn
 (common-lisp:defstruct (import-certificate-response (:copier common-lisp:nil))
   (certificate-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'import-certificate-response
                    'make-import-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          import-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:deftype in-use-list () '(trivial-types:proper-list string))
 (common-lisp:defun |make-in-use-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:deftype key-algorithm () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype key-algorithm-list ()
   '(trivial-types:proper-list key-algorithm))
 (common-lisp:defun |make-key-algorithm-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list key-algorithm))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (key-usage (:copier common-lisp:nil))
   (name common-lisp:nil :type
    (common-lisp:or key-usage-name common-lisp:null)))
 (common-lisp:export (common-lisp:list 'key-usage 'make-key-usage))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape key-usage))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name))))))
(common-lisp:progn
 (common-lisp:deftype key-usage-filter-list ()
   '(trivial-types:proper-list key-usage-name))
 (common-lisp:defun |make-key-usage-filter-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list key-usage-name))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype key-usage-list () '(trivial-types:proper-list key-usage))
 (common-lisp:defun |make-key-usage-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list key-usage))
   aws-sdk/generator/shape::members))
(common-lisp:deftype key-usage-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (list-certificates-request (:copier common-lisp:nil))
   (certificate-statuses common-lisp:nil :type
    (common-lisp:or certificate-statuses common-lisp:null))
   (includes common-lisp:nil :type (common-lisp:or filters common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (max-items common-lisp:nil :type
    (common-lisp:or max-items common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-certificates-request
                    'make-list-certificates-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-certificates-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateStatuses"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-statuses)))
    (aws-sdk/generator/shape::to-query-params "Includes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'includes)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "MaxItems"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-items))))))
(common-lisp:progn
 (common-lisp:defstruct (list-certificates-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (certificate-summary-list common-lisp:nil :type
    (common-lisp:or certificate-summary-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-certificates-response
                    'make-list-certificates-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-certificates-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "CertificateSummaryList"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-summary-list))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-certificate-request
                    'make-list-tags-for-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-tags-for-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-certificate-response (:copier common-lisp:nil))
   (tags common-lisp:nil :type (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-certificate-response
                    'make-list-tags-for-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-tags-for-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Tags"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tags))))))
(common-lisp:deftype max-items () 'common-lisp:integer)
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:deftype passphrase-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype positive-integer () 'common-lisp:integer)
(common-lisp:deftype private-key () 'common-lisp:string)
(common-lisp:deftype private-key-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:progn
 (common-lisp:defstruct
     (put-account-configuration-request (:copier common-lisp:nil))
   (expiry-events common-lisp:nil :type
    (common-lisp:or expiry-events-configuration common-lisp:null))
   (idempotency-token (common-lisp:error ":idempotency-token is required")
    :type (common-lisp:or idempotency-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-account-configuration-request
                    'make-put-account-configuration-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          put-account-configuration-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ExpiryEvents"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'expiry-events)))
    (aws-sdk/generator/shape::to-query-params "IdempotencyToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'idempotency-token))))))
(common-lisp:deftype record-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (remove-tags-from-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (tags (common-lisp:error ":tags is required") :type
    (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'remove-tags-from-certificate-request
                    'make-remove-tags-from-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          remove-tags-from-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Tags"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tags))))))
(common-lisp:progn
 (common-lisp:defstruct (renew-certificate-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'renew-certificate-request
                    'make-renew-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          renew-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:deftype renewal-eligibility () 'common-lisp:string)
(common-lisp:deftype renewal-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (renewal-summary (:copier common-lisp:nil))
   (renewal-status (common-lisp:error ":renewal-status is required") :type
    (common-lisp:or renewal-status common-lisp:null))
   (domain-validation-options
    (common-lisp:error ":domain-validation-options is required") :type
    (common-lisp:or domain-validation-list common-lisp:null))
   (renewal-status-reason common-lisp:nil :type
    (common-lisp:or failure-reason common-lisp:null))
   (updated-at (common-lisp:error ":updated-at is required") :type
    (common-lisp:or tstamp common-lisp:null)))
 (common-lisp:export (common-lisp:list 'renewal-summary 'make-renewal-summary))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape renewal-summary))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "RenewalStatus"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'renewal-status)))
    (aws-sdk/generator/shape::to-query-params "DomainValidationOptions"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-validation-options)))
    (aws-sdk/generator/shape::to-query-params "RenewalStatusReason"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'renewal-status-reason)))
    (aws-sdk/generator/shape::to-query-params "UpdatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'updated-at))))))
(common-lisp:progn
 (common-lisp:defstruct (request-certificate-request (:copier common-lisp:nil))
   (domain-name (common-lisp:error ":domain-name is required") :type
    (common-lisp:or domain-name-string common-lisp:null))
   (validation-method common-lisp:nil :type
    (common-lisp:or validation-method common-lisp:null))
   (subject-alternative-names common-lisp:nil :type
    (common-lisp:or domain-list common-lisp:null))
   (idempotency-token common-lisp:nil :type
    (common-lisp:or idempotency-token common-lisp:null))
   (domain-validation-options common-lisp:nil :type
    (common-lisp:or domain-validation-option-list common-lisp:null))
   (options common-lisp:nil :type
    (common-lisp:or certificate-options common-lisp:null))
   (certificate-authority-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null))
   (tags common-lisp:nil :type (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'request-certificate-request
                    'make-request-certificate-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          request-certificate-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DomainName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-name)))
    (aws-sdk/generator/shape::to-query-params "ValidationMethod"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-method)))
    (aws-sdk/generator/shape::to-query-params "SubjectAlternativeNames"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subject-alternative-names)))
    (aws-sdk/generator/shape::to-query-params "IdempotencyToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'idempotency-token)))
    (aws-sdk/generator/shape::to-query-params "DomainValidationOptions"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain-validation-options)))
    (aws-sdk/generator/shape::to-query-params "Options"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'options)))
    (aws-sdk/generator/shape::to-query-params "CertificateAuthorityArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-authority-arn)))
    (aws-sdk/generator/shape::to-query-params "Tags"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tags))))))
(common-lisp:progn
 (common-lisp:defstruct
     (request-certificate-response (:copier common-lisp:nil))
   (certificate-arn common-lisp:nil :type
    (common-lisp:or arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'request-certificate-response
                    'make-request-certificate-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          request-certificate-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (resend-validation-email-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (domain (common-lisp:error ":domain is required") :type
    (common-lisp:or domain-name-string common-lisp:null))
   (validation-domain (common-lisp:error ":validation-domain is required")
    :type (common-lisp:or domain-name-string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resend-validation-email-request
                    'make-resend-validation-email-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          resend-validation-email-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Domain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'domain)))
    (aws-sdk/generator/shape::to-query-params "ValidationDomain"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'validation-domain))))))
(common-lisp:progn
 (common-lisp:defstruct (resource-record (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or string common-lisp:null))
   (type (common-lisp:error ":type is required") :type
    (common-lisp:or record-type common-lisp:null))
   (value (common-lisp:error ":value is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'resource-record 'make-resource-record))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape resource-record))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "Type"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'type)))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'value))))))
(common-lisp:deftype revocation-reason () 'common-lisp:string)
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:deftype tstamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (tag (:copier common-lisp:nil))
   (key (common-lisp:error ":key is required") :type
    (common-lisp:or tag-key common-lisp:null))
   (value common-lisp:nil :type (common-lisp:or tag-value common-lisp:null)))
 (common-lisp:export (common-lisp:list 'tag 'make-tag))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape tag))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Key"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key)))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'value))))))
(common-lisp:deftype tag-key () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype tag-list () '(trivial-types:proper-list tag))
 (common-lisp:defun |make-tag-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list tag))
   aws-sdk/generator/shape::members))
(common-lisp:deftype tag-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (update-certificate-options-request (:copier common-lisp:nil))
   (certificate-arn (common-lisp:error ":certificate-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (options (common-lisp:error ":options is required") :type
    (common-lisp:or certificate-options common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-certificate-options-request
                    'make-update-certificate-options-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          update-certificate-options-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CertificateArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'certificate-arn)))
    (aws-sdk/generator/shape::to-query-params "Options"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'options))))))
(common-lisp:progn
 (common-lisp:deftype validation-email-list ()
   '(trivial-types:proper-list string))
 (common-lisp:defun |make-validation-email-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:deftype validation-method () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun add-tags-to-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn tags)
   (common-lisp:declare (common-lisp:ignorable certificate-arn tags))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-add-tags-to-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"AddTagsToCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'add-tags-to-certificate))
(common-lisp:progn
 (common-lisp:defun delete-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn)
   (common-lisp:declare (common-lisp:ignorable certificate-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"DeleteCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'delete-certificate))
(common-lisp:progn
 (common-lisp:defun describe-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn)
   (common-lisp:declare (common-lisp:ignorable certificate-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"DescribeCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DescribeCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'describe-certificate))
(common-lisp:progn
 (common-lisp:defun export-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn passphrase)
   (common-lisp:declare (common-lisp:ignorable certificate-arn passphrase))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-export-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ExportCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ExportCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'export-certificate))
(common-lisp:progn
 (common-lisp:defun get-account-configuration ()
   (aws-sdk/generator/operation::parse-response
    (aws-sdk/api:aws-request :service "acm" :method :post :params
                             `(("Action" ,@"GetAccountConfiguration")
                               ("Version" ,@"2015-12-08")))
    "GetAccountConfigurationResponse" common-lisp:nil))
 (common-lisp:export 'get-account-configuration))
(common-lisp:progn
 (common-lisp:defun get-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn)
   (common-lisp:declare (common-lisp:ignorable certificate-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"GetCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'get-certificate))
(common-lisp:progn
 (common-lisp:defun import-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn certificate private-key
                     certificate-chain tags)
   (common-lisp:declare
    (common-lisp:ignorable certificate-arn certificate private-key
     certificate-chain tags))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-import-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ImportCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ImportCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'import-certificate))
(common-lisp:progn
 (common-lisp:defun list-certificates
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-statuses includes next-token
                     max-items)
   (common-lisp:declare
    (common-lisp:ignorable certificate-statuses includes next-token max-items))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-certificates-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListCertificates")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListCertificatesResponse" common-lisp:nil)))
 (common-lisp:export 'list-certificates))
(common-lisp:progn
 (common-lisp:defun list-tags-for-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn)
   (common-lisp:declare (common-lisp:ignorable certificate-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-list-tags-for-certificate-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListTagsForCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListTagsForCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'list-tags-for-certificate))
(common-lisp:progn
 (common-lisp:defun put-account-configuration
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key expiry-events idempotency-token)
   (common-lisp:declare
    (common-lisp:ignorable expiry-events idempotency-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-put-account-configuration-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"PutAccountConfiguration")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-account-configuration))
(common-lisp:progn
 (common-lisp:defun remove-tags-from-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn tags)
   (common-lisp:declare (common-lisp:ignorable certificate-arn tags))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-remove-tags-from-certificate-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"RemoveTagsFromCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'remove-tags-from-certificate))
(common-lisp:progn
 (common-lisp:defun renew-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn)
   (common-lisp:declare (common-lisp:ignorable certificate-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-renew-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"RenewCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'renew-certificate))
(common-lisp:progn
 (common-lisp:defun request-certificate
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key domain-name validation-method
                     subject-alternative-names idempotency-token
                     domain-validation-options options
                     certificate-authority-arn tags)
   (common-lisp:declare
    (common-lisp:ignorable domain-name validation-method
     subject-alternative-names idempotency-token domain-validation-options
     options certificate-authority-arn tags))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-request-certificate-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"RequestCertificate")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "RequestCertificateResponse" common-lisp:nil)))
 (common-lisp:export 'request-certificate))
(common-lisp:progn
 (common-lisp:defun resend-validation-email
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn domain validation-domain)
   (common-lisp:declare
    (common-lisp:ignorable certificate-arn domain validation-domain))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-resend-validation-email-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ResendValidationEmail")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'resend-validation-email))
(common-lisp:progn
 (common-lisp:defun update-certificate-options
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key certificate-arn options)
   (common-lisp:declare (common-lisp:ignorable certificate-arn options))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-update-certificate-options-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "acm" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"UpdateCertificateOptions")
                                  ("Version" ,@"2015-12-08"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'update-certificate-options))
