;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/apigatewaymanagementapi
  (:use)
  (:nicknames #:aws/apigatewaymanagementapi)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/apigatewaymanagementapi)
(common-lisp:deftype data ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:progn
 (common-lisp:defstruct (delete-connection-request (:copier common-lisp:nil))
   (connection-id (common-lisp:error ":connection-id is required") :type
    (common-lisp:or |__string| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-connection-request
                    'make-delete-connection-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-connection-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ConnectionId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connection-id))))))
(common-lisp:progn
 (common-lisp:defstruct (get-connection-request (:copier common-lisp:nil))
   (connection-id (common-lisp:error ":connection-id is required") :type
    (common-lisp:or |__string| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-connection-request 'make-get-connection-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-connection-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ConnectionId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connection-id))))))
(common-lisp:progn
 (common-lisp:defstruct (get-connection-response (:copier common-lisp:nil))
   (connected-at common-lisp:nil :type
    (common-lisp:or |__timestampIso8601| common-lisp:null))
   (identity common-lisp:nil :type (common-lisp:or identity common-lisp:null))
   (last-active-at common-lisp:nil :type
    (common-lisp:or |__timestampIso8601| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-connection-response 'make-get-connection-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-connection-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ConnectedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connected-at)))
    (aws-sdk/generator/shape::to-query-params "Identity"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'identity)))
    (aws-sdk/generator/shape::to-query-params "LastActiveAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'last-active-at))))))
(common-lisp:progn
 (common-lisp:defstruct (identity (:copier common-lisp:nil))
   (source-ip (common-lisp:error ":source-ip is required") :type
    (common-lisp:or |__string| common-lisp:null))
   (user-agent (common-lisp:error ":user-agent is required") :type
    (common-lisp:or |__string| common-lisp:null)))
 (common-lisp:export (common-lisp:list 'identity 'make-identity))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape identity))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "SourceIp"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'source-ip)))
    (aws-sdk/generator/shape::to-query-params "UserAgent"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'user-agent))))))
(common-lisp:progn
 (common-lisp:defstruct (post-to-connection-request (:copier common-lisp:nil))
   (data (common-lisp:error ":data is required") :type
    (common-lisp:or data common-lisp:null))
   (connection-id (common-lisp:error ":connection-id is required") :type
    (common-lisp:or |__string| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'post-to-connection-request
                    'make-post-to-connection-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          post-to-connection-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Data"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'data)))
    (aws-sdk/generator/shape::to-query-params "ConnectionId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connection-id))))))
(common-lisp:deftype |__string| () 'common-lisp:string)
(common-lisp:deftype |__timestampIso8601| () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun delete-connection
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key connection-id)
   (common-lisp:declare (common-lisp:ignorable connection-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-connection-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "apigatewaymanagementapi" :method
                               :delete :params
                               (common-lisp:append
                                `(("Action" ,@"DeleteConnection")
                                  ("Version" ,@"2018-11-29"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'delete-connection))
(common-lisp:progn
 (common-lisp:defun get-connection
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key connection-id)
   (common-lisp:declare (common-lisp:ignorable connection-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-connection-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "apigatewaymanagementapi" :method :get
                               :params
                               (common-lisp:append
                                `(("Action" ,@"GetConnection")
                                  ("Version" ,@"2018-11-29"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetConnectionResponse" common-lisp:nil)))
 (common-lisp:export 'get-connection))
(common-lisp:progn
 (common-lisp:defun post-to-connection
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key data connection-id)
   (common-lisp:declare (common-lisp:ignorable data connection-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-post-to-connection-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "apigatewaymanagementapi" :method :post
                               :params
                               (common-lisp:append
                                `(("Action" ,@"PostToConnection")
                                  ("Version" ,@"2018-11-29"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'post-to-connection))
