;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/ec2-instance-connect
  (:use)
  (:nicknames #:aws/ec2-instance-connect)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/ec2-instance-connect)
(common-lisp:deftype availability-zone () 'common-lisp:string)
(common-lisp:deftype instance-id () 'common-lisp:string)
(common-lisp:deftype instance-osuser () 'common-lisp:string)
(common-lisp:deftype request-id () 'common-lisp:string)
(common-lisp:deftype sshpublic-key () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (send-sshpublic-key-request (:copier common-lisp:nil))
   (instance-id (common-lisp:error ":instance-id is required") :type
    (common-lisp:or instance-id common-lisp:null))
   (instance-osuser (common-lisp:error ":instance-osuser is required") :type
    (common-lisp:or instance-osuser common-lisp:null))
   (sshpublic-key (common-lisp:error ":sshpublic-key is required") :type
    (common-lisp:or sshpublic-key common-lisp:null))
   (availability-zone (common-lisp:error ":availability-zone is required")
    :type (common-lisp:or availability-zone common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'send-sshpublic-key-request
                    'make-send-sshpublic-key-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          send-sshpublic-key-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "InstanceId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-id)))
    (aws-sdk/generator/shape::to-query-params "InstanceOSUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-osuser)))
    (aws-sdk/generator/shape::to-query-params "SSHPublicKey"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'sshpublic-key)))
    (aws-sdk/generator/shape::to-query-params "AvailabilityZone"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'availability-zone))))))
(common-lisp:progn
 (common-lisp:defstruct (send-sshpublic-key-response (:copier common-lisp:nil))
   (request-id common-lisp:nil :type
    (common-lisp:or request-id common-lisp:null))
   (success common-lisp:nil :type (common-lisp:or success common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'send-sshpublic-key-response
                    'make-send-sshpublic-key-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          send-sshpublic-key-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "RequestId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'request-id)))
    (aws-sdk/generator/shape::to-query-params "Success"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'success))))))
(common-lisp:deftype success () 'common-lisp:boolean)
(common-lisp:progn
 (common-lisp:defun send-sshpublic-key
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key instance-id instance-osuser sshpublic-key
                     availability-zone)
   (common-lisp:declare
    (common-lisp:ignorable instance-id instance-osuser sshpublic-key
     availability-zone))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-send-sshpublic-key-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "ec2-instance-connect" :method :post
                               :params
                               (common-lisp:append
                                `(("Action" ,@"SendSSHPublicKey")
                                  ("Version" ,@"2018-04-02"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "SendSSHPublicKeyResponse" common-lisp:nil)))
 (common-lisp:export 'send-sshpublic-key))
