;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/redshift-data
  (:use)
  (:nicknames #:aws/redshift-data)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/redshift-data)
(common-lisp:deftype blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype boolean () 'common-lisp:boolean)
(common-lisp:deftype boxed-boolean () 'common-lisp:boolean)
(common-lisp:deftype boxed-double () 'common-lisp:double-float)
(common-lisp:deftype boxed-long () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (cancel-statement-request (:copier common-lisp:nil))
   (id (common-lisp:error ":id is required") :type
    (common-lisp:or uuid common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'cancel-statement-request 'make-cancel-statement-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          cancel-statement-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id))))))
(common-lisp:progn
 (common-lisp:defstruct (cancel-statement-response (:copier common-lisp:nil))
   (status common-lisp:nil :type (common-lisp:or boolean common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'cancel-statement-response
                    'make-cancel-statement-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          cancel-statement-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status))))))
(common-lisp:progn
 (common-lisp:deftype column-list ()
   '(trivial-types:proper-list column-metadata))
 (common-lisp:defun |make-column-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list column-metadata))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (column-metadata (:copier common-lisp:nil))
   (column-default common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (is-case-sensitive common-lisp:nil :type
    (common-lisp:or |bool| common-lisp:null))
   (is-currency common-lisp:nil :type (common-lisp:or |bool| common-lisp:null))
   (is-signed common-lisp:nil :type (common-lisp:or |bool| common-lisp:null))
   (label common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (length common-lisp:nil :type (common-lisp:or integer common-lisp:null))
   (name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (nullable common-lisp:nil :type (common-lisp:or integer common-lisp:null))
   (precision common-lisp:nil :type (common-lisp:or integer common-lisp:null))
   (scale common-lisp:nil :type (common-lisp:or integer common-lisp:null))
   (schema-name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (table-name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (type-name common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'column-metadata 'make-column-metadata))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape column-metadata))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "columnDefault"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'column-default)))
    (aws-sdk/generator/shape::to-query-params "isCaseSensitive"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'is-case-sensitive)))
    (aws-sdk/generator/shape::to-query-params "isCurrency"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'is-currency)))
    (aws-sdk/generator/shape::to-query-params "isSigned"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'is-signed)))
    (aws-sdk/generator/shape::to-query-params "label"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'label)))
    (aws-sdk/generator/shape::to-query-params "length"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'length)))
    (aws-sdk/generator/shape::to-query-params "name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "nullable"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'nullable)))
    (aws-sdk/generator/shape::to-query-params "precision"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'precision)))
    (aws-sdk/generator/shape::to-query-params "scale"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'scale)))
    (aws-sdk/generator/shape::to-query-params "schemaName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schema-name)))
    (aws-sdk/generator/shape::to-query-params "tableName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'table-name)))
    (aws-sdk/generator/shape::to-query-params "typeName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'type-name))))))
(common-lisp:progn
 (common-lisp:deftype column-metadata-list ()
   '(trivial-types:proper-list column-metadata))
 (common-lisp:defun |make-column-metadata-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list column-metadata))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype database-list () '(trivial-types:proper-list string))
 (common-lisp:defun |make-database-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (describe-statement-request (:copier common-lisp:nil))
   (id (common-lisp:error ":id is required") :type
    (common-lisp:or uuid common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-statement-request
                    'make-describe-statement-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-statement-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-statement-response (:copier common-lisp:nil))
   (cluster-identifier common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (database common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (duration common-lisp:nil :type (common-lisp:or long common-lisp:null))
   (error common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (has-result-set common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (id (common-lisp:error ":id is required") :type
    (common-lisp:or uuid common-lisp:null))
   (query-string common-lisp:nil :type
    (common-lisp:or statement-string common-lisp:null))
   (redshift-pid common-lisp:nil :type (common-lisp:or long common-lisp:null))
   (redshift-query-id common-lisp:nil :type
    (common-lisp:or long common-lisp:null))
   (result-rows common-lisp:nil :type (common-lisp:or long common-lisp:null))
   (result-size common-lisp:nil :type (common-lisp:or long common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or status-string common-lisp:null))
   (updated-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-statement-response
                    'make-describe-statement-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-statement-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "Duration"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'duration)))
    (aws-sdk/generator/shape::to-query-params "Error"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'error)))
    (aws-sdk/generator/shape::to-query-params "HasResultSet"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'has-result-set)))
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id)))
    (aws-sdk/generator/shape::to-query-params "QueryString"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'query-string)))
    (aws-sdk/generator/shape::to-query-params "RedshiftPid"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'redshift-pid)))
    (aws-sdk/generator/shape::to-query-params "RedshiftQueryId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'redshift-query-id)))
    (aws-sdk/generator/shape::to-query-params "ResultRows"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'result-rows)))
    (aws-sdk/generator/shape::to-query-params "ResultSize"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'result-size)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status)))
    (aws-sdk/generator/shape::to-query-params "UpdatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'updated-at))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-table-request (:copier common-lisp:nil))
   (cluster-identifier (common-lisp:error ":cluster-identifier is required")
    :type (common-lisp:or location common-lisp:null))
   (connected-database common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (database (common-lisp:error ":database is required") :type
    (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or page-size common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (schema common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null))
   (table common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-table-request 'make-describe-table-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-table-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "ConnectedDatabase"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connected-database)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "Schema"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schema)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn)))
    (aws-sdk/generator/shape::to-query-params "Table"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'table))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-table-response (:copier common-lisp:nil))
   (column-list common-lisp:nil :type
    (common-lisp:or column-list common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (table-name common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-table-response 'make-describe-table-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-table-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ColumnList"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'column-list)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "TableName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'table-name))))))
(common-lisp:progn
 (common-lisp:defstruct (execute-statement-input (:copier common-lisp:nil))
   (cluster-identifier (common-lisp:error ":cluster-identifier is required")
    :type (common-lisp:or location common-lisp:null))
   (database common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null))
   (sql (common-lisp:error ":sql is required") :type
    (common-lisp:or statement-string common-lisp:null))
   (statement-name common-lisp:nil :type
    (common-lisp:or statement-name-string common-lisp:null))
   (with-event common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'execute-statement-input 'make-execute-statement-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          execute-statement-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn)))
    (aws-sdk/generator/shape::to-query-params "Sql"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'sql)))
    (aws-sdk/generator/shape::to-query-params "StatementName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'statement-name)))
    (aws-sdk/generator/shape::to-query-params "WithEvent"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'with-event))))))
(common-lisp:progn
 (common-lisp:defstruct (execute-statement-output (:copier common-lisp:nil))
   (cluster-identifier common-lisp:nil :type
    (common-lisp:or location common-lisp:null))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (database common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (id common-lisp:nil :type (common-lisp:or uuid common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'execute-statement-output 'make-execute-statement-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          execute-statement-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (field (:copier common-lisp:nil))
   (blob-value common-lisp:nil :type (common-lisp:or blob common-lisp:null))
   (boolean-value common-lisp:nil :type
    (common-lisp:or boxed-boolean common-lisp:null))
   (double-value common-lisp:nil :type
    (common-lisp:or boxed-double common-lisp:null))
   (is-null common-lisp:nil :type
    (common-lisp:or boxed-boolean common-lisp:null))
   (long-value common-lisp:nil :type
    (common-lisp:or boxed-long common-lisp:null))
   (string-value common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'field 'make-field))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape field))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "blobValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'blob-value)))
    (aws-sdk/generator/shape::to-query-params "booleanValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'boolean-value)))
    (aws-sdk/generator/shape::to-query-params "doubleValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'double-value)))
    (aws-sdk/generator/shape::to-query-params "isNull"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'is-null)))
    (aws-sdk/generator/shape::to-query-params "longValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'long-value)))
    (aws-sdk/generator/shape::to-query-params "stringValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'string-value))))))
(common-lisp:progn
 (common-lisp:deftype field-list () '(trivial-types:proper-list field))
 (common-lisp:defun |make-field-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list field))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (get-statement-result-request (:copier common-lisp:nil))
   (id (common-lisp:error ":id is required") :type
    (common-lisp:or uuid common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-statement-result-request
                    'make-get-statement-result-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-statement-result-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-statement-result-response (:copier common-lisp:nil))
   (column-metadata common-lisp:nil :type
    (common-lisp:or column-metadata-list common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (records (common-lisp:error ":records is required") :type
    (common-lisp:or sql-records common-lisp:null))
   (total-num-rows common-lisp:nil :type
    (common-lisp:or long common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-statement-result-response
                    'make-get-statement-result-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-statement-result-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ColumnMetadata"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'column-metadata)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "Records"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'records)))
    (aws-sdk/generator/shape::to-query-params "TotalNumRows"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'total-num-rows))))))
(common-lisp:deftype integer () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (list-databases-request (:copier common-lisp:nil))
   (cluster-identifier (common-lisp:error ":cluster-identifier is required")
    :type (common-lisp:or location common-lisp:null))
   (database common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or page-size common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-databases-request 'make-list-databases-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-databases-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (list-databases-response (:copier common-lisp:nil))
   (databases common-lisp:nil :type
    (common-lisp:or database-list common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-databases-response 'make-list-databases-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-databases-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Databases"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'databases)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct (list-schemas-request (:copier common-lisp:nil))
   (cluster-identifier (common-lisp:error ":cluster-identifier is required")
    :type (common-lisp:or location common-lisp:null))
   (connected-database common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (database (common-lisp:error ":database is required") :type
    (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or page-size common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (schema-pattern common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-schemas-request 'make-list-schemas-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape list-schemas-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "ConnectedDatabase"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connected-database)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "SchemaPattern"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schema-pattern)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (list-schemas-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (schemas common-lisp:nil :type
    (common-lisp:or schema-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-schemas-response 'make-list-schemas-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-schemas-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "Schemas"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schemas))))))
(common-lisp:deftype list-statements-limit () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (list-statements-request (:copier common-lisp:nil))
   (max-results common-lisp:nil :type
    (common-lisp:or list-statements-limit common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (role-level common-lisp:nil :type (common-lisp:or boolean common-lisp:null))
   (statement-name common-lisp:nil :type
    (common-lisp:or statement-name-string common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or status-string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-statements-request 'make-list-statements-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-statements-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "RoleLevel"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'role-level)))
    (aws-sdk/generator/shape::to-query-params "StatementName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'statement-name)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status))))))
(common-lisp:progn
 (common-lisp:defstruct (list-statements-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (statements (common-lisp:error ":statements is required") :type
    (common-lisp:or statement-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-statements-response 'make-list-statements-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-statements-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "Statements"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'statements))))))
(common-lisp:progn
 (common-lisp:defstruct (list-tables-request (:copier common-lisp:nil))
   (cluster-identifier (common-lisp:error ":cluster-identifier is required")
    :type (common-lisp:or location common-lisp:null))
   (connected-database common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (database (common-lisp:error ":database is required") :type
    (common-lisp:or string common-lisp:null))
   (db-user common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or page-size common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (schema-pattern common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null))
   (table-pattern common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tables-request 'make-list-tables-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape list-tables-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ClusterIdentifier"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cluster-identifier)))
    (aws-sdk/generator/shape::to-query-params "ConnectedDatabase"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'connected-database)))
    (aws-sdk/generator/shape::to-query-params "Database"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'database)))
    (aws-sdk/generator/shape::to-query-params "DbUser"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'db-user)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "SchemaPattern"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schema-pattern)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn)))
    (aws-sdk/generator/shape::to-query-params "TablePattern"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'table-pattern))))))
(common-lisp:progn
 (common-lisp:defstruct (list-tables-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (tables common-lisp:nil :type (common-lisp:or table-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tables-response 'make-list-tables-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape list-tables-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "Tables"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tables))))))
(common-lisp:deftype location () 'common-lisp:string)
(common-lisp:deftype long () 'common-lisp:integer)
(common-lisp:deftype page-size () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:deftype schema-list () '(trivial-types:proper-list string))
 (common-lisp:defun |make-schema-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:deftype secret-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype sql-records () '(trivial-types:proper-list field-list))
 (common-lisp:defun |make-sql-records|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list field-list))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (statement-data (:copier common-lisp:nil))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (id (common-lisp:error ":id is required") :type
    (common-lisp:or uuid common-lisp:null))
   (query-string common-lisp:nil :type
    (common-lisp:or statement-string common-lisp:null))
   (secret-arn common-lisp:nil :type
    (common-lisp:or secret-arn common-lisp:null))
   (statement-name common-lisp:nil :type
    (common-lisp:or statement-name-string common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or status-string common-lisp:null))
   (updated-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export (common-lisp:list 'statement-data 'make-statement-data))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape statement-data))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "Id"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'id)))
    (aws-sdk/generator/shape::to-query-params "QueryString"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'query-string)))
    (aws-sdk/generator/shape::to-query-params "SecretArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-arn)))
    (aws-sdk/generator/shape::to-query-params "StatementName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'statement-name)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status)))
    (aws-sdk/generator/shape::to-query-params "UpdatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'updated-at))))))
(common-lisp:progn
 (common-lisp:deftype statement-list ()
   '(trivial-types:proper-list statement-data))
 (common-lisp:defun |make-statement-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list statement-data))
   aws-sdk/generator/shape::members))
(common-lisp:deftype statement-name-string () 'common-lisp:string)
(common-lisp:deftype statement-string () 'common-lisp:string)
(common-lisp:deftype status-string () 'common-lisp:string)
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype table-list () '(trivial-types:proper-list table-member))
 (common-lisp:defun |make-table-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list table-member))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (table-member (:copier common-lisp:nil))
   (name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (schema common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (type common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'table-member 'make-table-member))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape table-member))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "schema"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'schema)))
    (aws-sdk/generator/shape::to-query-params "type"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'type))))))
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:deftype uuid () 'common-lisp:string)
(common-lisp:deftype |bool| () 'common-lisp:boolean)
(common-lisp:progn
 (common-lisp:defun cancel-statement
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key id)
   (common-lisp:declare (common-lisp:ignorable id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-cancel-statement-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"CancelStatement")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "CancelStatementResponse" common-lisp:nil)))
 (common-lisp:export 'cancel-statement))
(common-lisp:progn
 (common-lisp:defun describe-statement
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key id)
   (common-lisp:declare (common-lisp:ignorable id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-statement-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"DescribeStatement")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DescribeStatementResponse" common-lisp:nil)))
 (common-lisp:export 'describe-statement))
(common-lisp:progn
 (common-lisp:defun describe-table
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key cluster-identifier connected-database
                     database db-user max-results next-token schema secret-arn
                     table)
   (common-lisp:declare
    (common-lisp:ignorable cluster-identifier connected-database database
     db-user max-results next-token schema secret-arn table))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-table-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"DescribeTable")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DescribeTableResponse" common-lisp:nil)))
 (common-lisp:export 'describe-table))
(common-lisp:progn
 (common-lisp:defun execute-statement
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key cluster-identifier database db-user
                     secret-arn sql statement-name with-event)
   (common-lisp:declare
    (common-lisp:ignorable cluster-identifier database db-user secret-arn sql
     statement-name with-event))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-execute-statement-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ExecuteStatement")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ExecuteStatementOutput" common-lisp:nil)))
 (common-lisp:export 'execute-statement))
(common-lisp:progn
 (common-lisp:defun get-statement-result
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key id next-token)
   (common-lisp:declare (common-lisp:ignorable id next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-statement-result-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"GetStatementResult")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetStatementResultResponse" common-lisp:nil)))
 (common-lisp:export 'get-statement-result))
(common-lisp:progn
 (common-lisp:defun list-databases
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key cluster-identifier database db-user
                     max-results next-token secret-arn)
   (common-lisp:declare
    (common-lisp:ignorable cluster-identifier database db-user max-results
     next-token secret-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-databases-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListDatabases")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListDatabasesResponse" common-lisp:nil)))
 (common-lisp:export 'list-databases))
(common-lisp:progn
 (common-lisp:defun list-schemas
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key cluster-identifier connected-database
                     database db-user max-results next-token schema-pattern
                     secret-arn)
   (common-lisp:declare
    (common-lisp:ignorable cluster-identifier connected-database database
     db-user max-results next-token schema-pattern secret-arn))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-schemas-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListSchemas")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListSchemasResponse" common-lisp:nil)))
 (common-lisp:export 'list-schemas))
(common-lisp:progn
 (common-lisp:defun list-statements
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key max-results next-token role-level
                     statement-name status)
   (common-lisp:declare
    (common-lisp:ignorable max-results next-token role-level statement-name
     status))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-statements-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListStatements")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListStatementsResponse" common-lisp:nil)))
 (common-lisp:export 'list-statements))
(common-lisp:progn
 (common-lisp:defun list-tables
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key cluster-identifier connected-database
                     database db-user max-results next-token schema-pattern
                     secret-arn table-pattern)
   (common-lisp:declare
    (common-lisp:ignorable cluster-identifier connected-database database
     db-user max-results next-token schema-pattern secret-arn table-pattern))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-tables-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "redshift-data" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"ListTables")
                                  ("Version" ,@"2019-12-20"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListTablesResponse" common-lisp:nil)))
 (common-lisp:export 'list-tables))
