;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/runtime.sagemaker
  (:use)
  (:nicknames #:aws/runtime.sagemaker)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/runtime.sagemaker)
(common-lisp:deftype body-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype custom-attributes-header () 'common-lisp:string)
(common-lisp:deftype endpoint-name () 'common-lisp:string)
(common-lisp:deftype header () 'common-lisp:string)
(common-lisp:deftype inference-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (invoke-endpoint-input (:copier common-lisp:nil))
   (endpoint-name (common-lisp:error ":endpoint-name is required") :type
    (common-lisp:or endpoint-name common-lisp:null))
   (body (common-lisp:error ":body is required") :type
    (common-lisp:or body-blob common-lisp:null))
   (content-type common-lisp:nil :type
    (common-lisp:or header common-lisp:null))
   (accept common-lisp:nil :type (common-lisp:or header common-lisp:null))
   (custom-attributes common-lisp:nil :type
    (common-lisp:or custom-attributes-header common-lisp:null))
   (target-model common-lisp:nil :type
    (common-lisp:or target-model-header common-lisp:null))
   (target-variant common-lisp:nil :type
    (common-lisp:or target-variant-header common-lisp:null))
   (target-container-hostname common-lisp:nil :type
    (common-lisp:or target-container-hostname-header common-lisp:null))
   (inference-id common-lisp:nil :type
    (common-lisp:or inference-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invoke-endpoint-input 'make-invoke-endpoint-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invoke-endpoint-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "EndpointName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'endpoint-name)))
    (aws-sdk/generator/shape::to-query-params "Body"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'body)))
    (aws-sdk/generator/shape::to-query-params "ContentType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'content-type)))
    (aws-sdk/generator/shape::to-query-params "Accept"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'accept)))
    (aws-sdk/generator/shape::to-query-params "CustomAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'custom-attributes)))
    (aws-sdk/generator/shape::to-query-params "TargetModel"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'target-model)))
    (aws-sdk/generator/shape::to-query-params "TargetVariant"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'target-variant)))
    (aws-sdk/generator/shape::to-query-params "TargetContainerHostname"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'target-container-hostname)))
    (aws-sdk/generator/shape::to-query-params "InferenceId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'inference-id))))))
(common-lisp:progn
 (common-lisp:defstruct (invoke-endpoint-output (:copier common-lisp:nil))
   (body (common-lisp:error ":body is required") :type
    (common-lisp:or body-blob common-lisp:null))
   (content-type common-lisp:nil :type
    (common-lisp:or header common-lisp:null))
   (invoked-production-variant common-lisp:nil :type
    (common-lisp:or header common-lisp:null))
   (custom-attributes common-lisp:nil :type
    (common-lisp:or custom-attributes-header common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invoke-endpoint-output 'make-invoke-endpoint-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invoke-endpoint-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Body"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'body)))
    (aws-sdk/generator/shape::to-query-params "ContentType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'content-type)))
    (aws-sdk/generator/shape::to-query-params "InvokedProductionVariant"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'invoked-production-variant)))
    (aws-sdk/generator/shape::to-query-params "CustomAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'custom-attributes))))))
(common-lisp:deftype target-container-hostname-header () 'common-lisp:string)
(common-lisp:deftype target-model-header () 'common-lisp:string)
(common-lisp:deftype target-variant-header () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun invoke-endpoint
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key endpoint-name body content-type accept
                     custom-attributes target-model target-variant
                     target-container-hostname inference-id)
   (common-lisp:declare
    (common-lisp:ignorable endpoint-name body content-type accept
     custom-attributes target-model target-variant target-container-hostname
     inference-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-invoke-endpoint-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "runtime.sagemaker" :method :post
                               :params
                               (common-lisp:append
                                `(("Action" ,@"InvokeEndpoint")
                                  ("Version" ,@"2017-05-13"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "InvokeEndpointOutput" common-lisp:nil)))
 (common-lisp:export 'invoke-endpoint))
