;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/sagemaker-edge
  (:use)
  (:nicknames #:aws/sagemaker-edge)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/sagemaker-edge)
(common-lisp:deftype cache-ttlseconds () 'common-lisp:string)
(common-lisp:deftype device-fleet-name () 'common-lisp:string)
(common-lisp:deftype device-name () 'common-lisp:string)
(common-lisp:deftype device-registration () 'common-lisp:string)
(common-lisp:deftype dimension () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (edge-metric (:copier common-lisp:nil))
   (dimension common-lisp:nil :type
    (common-lisp:or dimension common-lisp:null))
   (metric-name common-lisp:nil :type (common-lisp:or metric common-lisp:null))
   (value common-lisp:nil :type (common-lisp:or value common-lisp:null))
   (timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export (common-lisp:list 'edge-metric 'make-edge-metric))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape edge-metric))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Dimension"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'dimension)))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'metric-name)))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'value)))
    (aws-sdk/generator/shape::to-query-params "Timestamp"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'timestamp))))))
(common-lisp:progn
 (common-lisp:deftype edge-metrics () '(trivial-types:proper-list edge-metric))
 (common-lisp:defun |make-edge-metrics|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list edge-metric))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (get-device-registration-request (:copier common-lisp:nil))
   (device-name (common-lisp:error ":device-name is required") :type
    (common-lisp:or device-name common-lisp:null))
   (device-fleet-name (common-lisp:error ":device-fleet-name is required")
    :type (common-lisp:or device-fleet-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-device-registration-request
                    'make-get-device-registration-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-device-registration-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DeviceName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'device-name)))
    (aws-sdk/generator/shape::to-query-params "DeviceFleetName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'device-fleet-name))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-device-registration-result (:copier common-lisp:nil))
   (device-registration common-lisp:nil :type
    (common-lisp:or device-registration common-lisp:null))
   (cache-ttl common-lisp:nil :type
    (common-lisp:or cache-ttlseconds common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-device-registration-result
                    'make-get-device-registration-result))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-device-registration-result))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DeviceRegistration"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'device-registration)))
    (aws-sdk/generator/shape::to-query-params "CacheTTL"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cache-ttl))))))
(common-lisp:deftype metric () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (model (:copier common-lisp:nil))
   (model-name common-lisp:nil :type
    (common-lisp:or model-name common-lisp:null))
   (model-version common-lisp:nil :type
    (common-lisp:or version common-lisp:null))
   (latest-sample-time common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (latest-inference common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (model-metrics common-lisp:nil :type
    (common-lisp:or edge-metrics common-lisp:null)))
 (common-lisp:export (common-lisp:list 'model 'make-model))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape model))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ModelName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'model-name)))
    (aws-sdk/generator/shape::to-query-params "ModelVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'model-version)))
    (aws-sdk/generator/shape::to-query-params "LatestSampleTime"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'latest-sample-time)))
    (aws-sdk/generator/shape::to-query-params "LatestInference"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'latest-inference)))
    (aws-sdk/generator/shape::to-query-params "ModelMetrics"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'model-metrics))))))
(common-lisp:deftype model-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype models () '(trivial-types:proper-list model))
 (common-lisp:defun |make-models|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list model))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (send-heartbeat-request (:copier common-lisp:nil))
   (agent-metrics common-lisp:nil :type
    (common-lisp:or edge-metrics common-lisp:null))
   (models common-lisp:nil :type (common-lisp:or models common-lisp:null))
   (agent-version (common-lisp:error ":agent-version is required") :type
    (common-lisp:or version common-lisp:null))
   (device-name (common-lisp:error ":device-name is required") :type
    (common-lisp:or device-name common-lisp:null))
   (device-fleet-name (common-lisp:error ":device-fleet-name is required")
    :type (common-lisp:or device-fleet-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'send-heartbeat-request 'make-send-heartbeat-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          send-heartbeat-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AgentMetrics"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'agent-metrics)))
    (aws-sdk/generator/shape::to-query-params "Models"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'models)))
    (aws-sdk/generator/shape::to-query-params "AgentVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'agent-version)))
    (aws-sdk/generator/shape::to-query-params "DeviceName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'device-name)))
    (aws-sdk/generator/shape::to-query-params "DeviceFleetName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'device-fleet-name))))))
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:deftype value () 'common-lisp:double-float)
(common-lisp:deftype version () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun get-device-registration
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key device-name device-fleet-name)
   (common-lisp:declare (common-lisp:ignorable device-name device-fleet-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-device-registration-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sagemaker-edge" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"GetDeviceRegistration")
                                  ("Version" ,@"2020-09-23"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetDeviceRegistrationResult" common-lisp:nil)))
 (common-lisp:export 'get-device-registration))
(common-lisp:progn
 (common-lisp:defun send-heartbeat
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key agent-metrics models agent-version
                     device-name device-fleet-name)
   (common-lisp:declare
    (common-lisp:ignorable agent-metrics models agent-version device-name
     device-fleet-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-send-heartbeat-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sagemaker-edge" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"SendHeartbeat")
                                  ("Version" ,@"2020-09-23"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'send-heartbeat))
