;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/sso
  (:use)
  (:nicknames #:aws/sso)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/sso)
(common-lisp:deftype access-key-type () 'common-lisp:string)
(common-lisp:deftype access-token-type () 'common-lisp:string)
(common-lisp:deftype account-id-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (account-info (:copier common-lisp:nil))
   (account-id common-lisp:nil :type
    (common-lisp:or account-id-type common-lisp:null))
   (account-name common-lisp:nil :type
    (common-lisp:or account-name-type common-lisp:null))
   (email-address common-lisp:nil :type
    (common-lisp:or email-address-type common-lisp:null)))
 (common-lisp:export (common-lisp:list 'account-info 'make-account-info))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape account-info))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "accountId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-id)))
    (aws-sdk/generator/shape::to-query-params "accountName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-name)))
    (aws-sdk/generator/shape::to-query-params "emailAddress"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'email-address))))))
(common-lisp:progn
 (common-lisp:deftype account-list-type ()
   '(trivial-types:proper-list account-info))
 (common-lisp:defun |make-account-list-type|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list account-info))
   aws-sdk/generator/shape::members))
(common-lisp:deftype account-name-type () 'common-lisp:string)
(common-lisp:deftype email-address-type () 'common-lisp:string)
(common-lisp:deftype expiration-timestamp-type () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct
     (get-role-credentials-request (:copier common-lisp:nil))
   (role-name (common-lisp:error ":rolename is required") :type
    (common-lisp:or role-name-type common-lisp:null))
   (account-id (common-lisp:error ":accountid is required") :type
    (common-lisp:or account-id-type common-lisp:null))
   (access-token (common-lisp:error ":accesstoken is required") :type
    (common-lisp:or access-token-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-role-credentials-request
                    'make-get-role-credentials-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-role-credentials-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "roleName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'role-name)))
    (aws-sdk/generator/shape::to-query-params "accountId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-id)))
    (aws-sdk/generator/shape::to-query-params "accessToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'access-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-role-credentials-response (:copier common-lisp:nil))
   (role-credentials common-lisp:nil :type
    (common-lisp:or role-credentials common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-role-credentials-response
                    'make-get-role-credentials-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-role-credentials-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "roleCredentials"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'role-credentials))))))
(common-lisp:progn
 (common-lisp:defstruct (list-account-roles-request (:copier common-lisp:nil))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token-type common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-result-type common-lisp:null))
   (access-token (common-lisp:error ":accesstoken is required") :type
    (common-lisp:or access-token-type common-lisp:null))
   (account-id (common-lisp:error ":accountid is required") :type
    (common-lisp:or account-id-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-account-roles-request
                    'make-list-account-roles-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-account-roles-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "nextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "maxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "accessToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'access-token)))
    (aws-sdk/generator/shape::to-query-params "accountId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-id))))))
(common-lisp:progn
 (common-lisp:defstruct (list-account-roles-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token-type common-lisp:null))
   (role-list common-lisp:nil :type
    (common-lisp:or role-list-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-account-roles-response
                    'make-list-account-roles-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-account-roles-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "nextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "roleList"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'role-list))))))
(common-lisp:progn
 (common-lisp:defstruct (list-accounts-request (:copier common-lisp:nil))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token-type common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-result-type common-lisp:null))
   (access-token (common-lisp:error ":accesstoken is required") :type
    (common-lisp:or access-token-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-accounts-request 'make-list-accounts-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-accounts-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "nextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "maxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results)))
    (aws-sdk/generator/shape::to-query-params "accessToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'access-token))))))
(common-lisp:progn
 (common-lisp:defstruct (list-accounts-response (:copier common-lisp:nil))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token-type common-lisp:null))
   (account-list common-lisp:nil :type
    (common-lisp:or account-list-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-accounts-response 'make-list-accounts-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-accounts-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "nextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "accountList"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-list))))))
(common-lisp:progn
 (common-lisp:defstruct (logout-request (:copier common-lisp:nil))
   (access-token (common-lisp:error ":accesstoken is required") :type
    (common-lisp:or access-token-type common-lisp:null)))
 (common-lisp:export (common-lisp:list 'logout-request 'make-logout-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape logout-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "accessToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'access-token))))))
(common-lisp:deftype max-result-type () 'common-lisp:integer)
(common-lisp:deftype next-token-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (role-credentials (:copier common-lisp:nil))
   (access-key-id common-lisp:nil :type
    (common-lisp:or access-key-type common-lisp:null))
   (secret-access-key common-lisp:nil :type
    (common-lisp:or secret-access-key-type common-lisp:null))
   (session-token common-lisp:nil :type
    (common-lisp:or session-token-type common-lisp:null))
   (expiration common-lisp:nil :type
    (common-lisp:or expiration-timestamp-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'role-credentials 'make-role-credentials))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape role-credentials))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "accessKeyId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'access-key-id)))
    (aws-sdk/generator/shape::to-query-params "secretAccessKey"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'secret-access-key)))
    (aws-sdk/generator/shape::to-query-params "sessionToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'session-token)))
    (aws-sdk/generator/shape::to-query-params "expiration"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'expiration))))))
(common-lisp:progn
 (common-lisp:defstruct (role-info (:copier common-lisp:nil))
   (role-name common-lisp:nil :type
    (common-lisp:or role-name-type common-lisp:null))
   (account-id common-lisp:nil :type
    (common-lisp:or account-id-type common-lisp:null)))
 (common-lisp:export (common-lisp:list 'role-info 'make-role-info))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape role-info))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "roleName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'role-name)))
    (aws-sdk/generator/shape::to-query-params "accountId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'account-id))))))
(common-lisp:progn
 (common-lisp:deftype role-list-type () '(trivial-types:proper-list role-info))
 (common-lisp:defun |make-role-list-type|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list role-info))
   aws-sdk/generator/shape::members))
(common-lisp:deftype role-name-type () 'common-lisp:string)
(common-lisp:deftype secret-access-key-type () 'common-lisp:string)
(common-lisp:deftype session-token-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun get-role-credentials
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key role-name account-id access-token)
   (common-lisp:declare
    (common-lisp:ignorable role-name account-id access-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-role-credentials-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sso" :method :get :params
                               (common-lisp:append
                                `(("Action" ,@"GetRoleCredentials")
                                  ("Version" ,@"2019-06-10"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetRoleCredentialsResponse" common-lisp:nil)))
 (common-lisp:export 'get-role-credentials))
(common-lisp:progn
 (common-lisp:defun list-account-roles
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key next-token max-results access-token
                     account-id)
   (common-lisp:declare
    (common-lisp:ignorable next-token max-results access-token account-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-account-roles-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sso" :method :get :params
                               (common-lisp:append
                                `(("Action" ,@"ListAccountRoles")
                                  ("Version" ,@"2019-06-10"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListAccountRolesResponse" common-lisp:nil)))
 (common-lisp:export 'list-account-roles))
(common-lisp:progn
 (common-lisp:defun list-accounts
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key next-token max-results access-token)
   (common-lisp:declare
    (common-lisp:ignorable next-token max-results access-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-accounts-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sso" :method :get :params
                               (common-lisp:append
                                `(("Action" ,@"ListAccounts")
                                  ("Version" ,@"2019-06-10"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "ListAccountsResponse" common-lisp:nil)))
 (common-lisp:export 'list-accounts))
(common-lisp:progn
 (common-lisp:defun logout
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key access-token)
   (common-lisp:declare (common-lisp:ignorable access-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-logout-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "sso" :method :post :params
                               (common-lisp:append
                                `(("Action" ,@"Logout")
                                  ("Version" ,@"2019-06-10"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'logout))
