;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/workmailmessageflow
  (:use)
  (:nicknames #:aws/workmailmessageflow)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/workmailmessageflow)
(common-lisp:progn
 (common-lisp:defstruct
     (get-raw-message-content-request (:copier common-lisp:nil))
   (message-id (common-lisp:error ":messageid is required") :type
    (common-lisp:or |messageIdType| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-raw-message-content-request
                    'make-get-raw-message-content-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-raw-message-content-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "messageId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-raw-message-content-response (:copier common-lisp:nil))
   (message-content (common-lisp:error ":messagecontent is required") :type
    (common-lisp:or |messageContentBlob| common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-raw-message-content-response
                    'make-get-raw-message-content-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-raw-message-content-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "messageContent"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message-content))))))
(common-lisp:progn
 (common-lisp:defstruct
     (put-raw-message-content-request (:copier common-lisp:nil))
   (message-id (common-lisp:error ":messageid is required") :type
    (common-lisp:or |messageIdType| common-lisp:null))
   (content (common-lisp:error ":content is required") :type
    (common-lisp:or raw-message-content common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-raw-message-content-request
                    'make-put-raw-message-content-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          put-raw-message-content-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "messageId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message-id)))
    (aws-sdk/generator/shape::to-query-params "content"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'content))))))
(common-lisp:progn
 (common-lisp:defstruct
     (put-raw-message-content-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'put-raw-message-content-response
                    'make-put-raw-message-content-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          put-raw-message-content-response))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (raw-message-content (:copier common-lisp:nil))
   (s3reference (common-lisp:error ":s3reference is required") :type
    (common-lisp:or s3reference common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'raw-message-content 'make-raw-message-content))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape raw-message-content))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "s3Reference"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                's3reference))))))
(common-lisp:progn
 (common-lisp:defstruct (s3reference (:copier common-lisp:nil))
   (bucket (common-lisp:error ":bucket is required") :type
    (common-lisp:or |s3BucketIdType| common-lisp:null))
   (key (common-lisp:error ":key is required") :type
    (common-lisp:or |s3KeyIdType| common-lisp:null))
   (object-version common-lisp:nil :type
    (common-lisp:or |s3VersionType| common-lisp:null)))
 (common-lisp:export (common-lisp:list 's3reference 'make-s3reference))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape s3reference))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "bucket"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'bucket)))
    (aws-sdk/generator/shape::to-query-params "key"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key)))
    (aws-sdk/generator/shape::to-query-params "objectVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'object-version))))))
(common-lisp:deftype |messageContentBlob| ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype |messageIdType| () 'common-lisp:string)
(common-lisp:deftype |s3BucketIdType| () 'common-lisp:string)
(common-lisp:deftype |s3KeyIdType| () 'common-lisp:string)
(common-lisp:deftype |s3VersionType| () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun get-raw-message-content
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key message-id)
   (common-lisp:declare (common-lisp:ignorable message-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-raw-message-content-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "workmailmessageflow" :method :get
                               :params
                               (common-lisp:append
                                `(("Action" ,@"GetRawMessageContent")
                                  ("Version" ,@"2019-05-01"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetRawMessageContentResponse" common-lisp:nil)))
 (common-lisp:export 'get-raw-message-content))
(common-lisp:progn
 (common-lisp:defun put-raw-message-content
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key message-id content)
   (common-lisp:declare (common-lisp:ignorable message-id content))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-put-raw-message-content-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "workmailmessageflow" :method :post
                               :params
                               (common-lisp:append
                                `(("Action" ,@"PutRawMessageContent")
                                  ("Version" ,@"2019-05-01"))
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "PutRawMessageContentResponse" common-lisp:nil)))
 (common-lisp:export 'put-raw-message-content))
